# Gradle
org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Kotlin
kotlin.code.style=official
kotlin.incremental=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# App version (used by the desktop native distribution and the Android APK)
version_name=2.2.0
version_code=11
